{{- if .Values.global.networkPolicy.enabled -}}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ template "eric-oss-pm-stats-calc-handling.name" . }}-log-transformer-allow
  labels:
  {{- include "eric-oss-pm-stats-calc-handling.kubernetes-io-info" . | nindent 4 }}
  annotations:
  {{- include "eric-oss-pm-stats-calc-handling.helm-annotations" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: eric-log-transformer
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: eric-oss-pm-stats-calculator
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: eric-oss-pm-stats-exporter
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: eric-oss-pm-stats-query-service
  policyTypes:
  - Ingress
{{- end }}