#
# COPYRIGHT Ericsson 2022
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{- if index .Values "apiGWRouteQueryService" "enabled" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "eric-oss-pm-stats-calc-handling.name" . }}-queryservice-deletes-route-hook
  labels:
    {{- include "eric-oss-pm-stats-calc-handling.kubernetes-io-info" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-delete, post-rollback
    "helm.sh/hook-delete-policy": "hook-succeeded, before-hook-creation"
    {{- include "eric-oss-pm-stats-calc-handling.helm-annotations" . | nindent 4 }}
spec:
  activeDeadlineSeconds: 1800
  backoffLimit: 1800
  template:
    metadata:
      labels:
      {{- include "eric-oss-pm-stats-calc-handling.kubernetes-io-info" . | nindent 8 }}
      annotations:
      {{- include "eric-oss-pm-stats-calc-handling.helm-annotations" . | nindent 8 }}
    spec:
      serviceAccountName: {{ template "eric-oss-pm-stats-calc-handling.name" . }}-sa
      {{- if include "eric-oss-pm-stats-calc-handling.pullSecrets" . }}
      imagePullSecrets:
        - name: {{ include "eric-oss-pm-stats-calc-handling.pullSecrets" . }}
      {{- end }}
      restartPolicy: Never
      {{- if or .Values.tolerations (and .Values.global .Values.global.tolerations) }}
      tolerations:
      {{- include "eric-oss-pm-stats-calc-handling.tolerations" . | nindent 8 }}
      {{- end }}
      containers:
        - name: api-gateway-client
          image: {{ template "eric-oss-pm-stats-calc-handling.imagePath" (dict "imageId" "api-gateway-client" "values" .Values "files" .Files) }}
          imagePullPolicy: {{ .Values.global.registry.imagePullPolicy }}
          env:
          - name: SYSTEM_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.apiGatewayRoute.credentials.name | quote }}
                key: {{ .Values.apiGatewayRoute.credentials.userKey | quote }}
          - name: SYSTEM_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.apiGatewayRoute.credentials.name | quote }}
                key: {{ .Values.apiGatewayRoute.credentials.pwdKey | quote }}
          args:
          - "{{ index .Values.apiGWRouteQueryService.routePath.tag }}"
          - "https://{{.Values.global.hosts.gas}}/auth/v1/login/"
          - "$(SYSTEM_USER)"
          - "$(SYSTEM_USER_PASSWORD)"
          - "delete"
          - "{{ index .Values.apiGWRouteQueryService.routePath.routeId }}"
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 40514
            capabilities:
              drop:
                - "all"
{{- end }}

